### ISSUE TITLE
udroid user for raw build

### ISSUE THREAD

**Issue by SaicharanKandukuri** [RandomCoderOrg/fs-cook#6]
need to make code to make <kbd>udroid</kbd> user in raw rootfs builds

- [x] add/upgrade post build chroot command execution function
- [x] make snippets to add user
- [x] add trigger to run script in chroot with switch
- [x] make Docker images
- [x] make test
- [x] push to master ( production build )
- [ ] fix issues with user ( string issues )

**Comment by SaicharanKandukuri** [comment]
interested in helping, make sure you notice me here with the task you want to do here.

###### please follow [code of conduct](https://github.com/RandomCoderOrg/fs-manager-udroid/blob/main/CODE_OF_CONDUCT.md)

**Comment by AnninoDr4** [comment]
@SaicharanKandukuri leave 1 & 2 i'll do that

**Comment by SaicharanKandukuri** [comment]
sure

**Comment by AnninoDr4** [comment]
@SaicharanKandukuri its Done
now its time for you to test

**Comment by SaicharanKandukuri** [comment]
I'll do it soon
need to attend classes

**Comment by SaicharanKandukuri** [comment]
ok there are some string issues
need to do backtrace

**Comment by SaicharanKandukuri** [comment]
need to
